#! /usr/bin/env bash
set -e

MAC=$2

if [[ $1 == "-r" ]]; then
    if [[ $MAC == *":"* ]]; then
        echo ${MAC//:}
        exit 0
    fi

    if [[ $MAC == *"-"* ]]; then
        echo ${MAC//-}
        exit 0
    fi
fi

if [[ $1 == "-c" ]] && [[ ${#MAC} == 12 ]]; then
    echo ${MAC:0:2}:${MAC:2:2}:${MAC:4:2}:${MAC:6:2}:${MAC:8:2}:${MAC:10:2}
    exit 0
fi


if [[ $1 == "-d" ]] && [[ ${#MAC} == 12 ]]; then
    echo ${MAC:0:2}-${MAC:2:2}-${MAC:4:2}-${MAC:6:2}-${MAC:8:2}-${MAC:10:2}
    exit 0
fi


echo "Usage: [-r|-c|-d] [MAC ADDRESS]"
echo
echo -r remove any dilimeters
echo -c add colons
echo -d add dashed
exit 65
